openapi: 3.0.3
info:
  title : 'API MuseumGO'
  version : 0.1.0
  description : 'A swagger Museum as you never be able to be that swag'
paths:
  /works:
    get:
      operationId: controller.works.get_works
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - museum
                - work
      responses:
        "200":
          description: List of works
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Work"

components:
  schemas:
    Work:
      type: object
      properties:
        name:
          type: string
          description: The work ID
        position:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
