openapi: 3.0.3
info:
  title: "API MuseumGO"
  version: 0.1.2
  description: "A swagger Museum as you never be able to be that swag"
paths:
  /works:
    get:
      operationId: controller.works.get_works
      description: Get all works
      parameters:
        - name: searchField
          in: query
          description: The text to search, if empty return all works,
            Filter the things you want to see with the name, artist, tags and description
          required: false
          schema:
            type: string
            minLength: 1
            example: "Mona Lisa"

      responses:
        "200":
          description: List of works
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Work"

components:
  schemas:
    Work:
      type: object
      description: A work of art
      properties:
        name:
          type: string
          description: The work ID
        position:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
          required:
            - latitude
            - longitude
      required:
        - name
        - position