openapi: 3.0.3
info:
  title: "API MuseumGO"
  description: "The Museum GO API"
  version: "0.0.0"
paths:
  /works:
    get:
      operationId: controller.works.get_works
      description: Get all works
      parameters:
        - name: searchField
          in: query
          description: The text to search, if empty return all works,
            Filter the things you want to see with the name, artist, tags and description
          required: false
          schema:
            type: string
            minLength: 1
            example: "Mona Lisa"

      responses:
        "200":
          description: List of works
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Work"
  /worksInRectangle:
    get:
      operationId: controller.works.get_works_rect
      description: Get works that are in a range of a point
      parameters:
        - name: bottomLeftLat
          in: query
          description: The latitude of the top left point
          required: true
          schema:
            type: number
            format: double
            example: 41.40338
        - name: bottomLeftLon
          in: query
          description: The longitude of the top left point
          required: true
          schema:
            type: number
            format: double
            example: 2.17403
        - name: topRightLat
          in: query
          description: The latitude of the bottom right point
          required: true
          schema:
            type: number
            format: double
            example: 42.40338
        - name: topRightLon
          in: query
          description: The longitude of the bottom right point
          required: true
          schema:
            type: number
            format: double
            example: 3.17403

      responses:
        "200":
          description: List of works in range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WorkWithDistance"

components:
  schemas:
    Work:
      type: object
      description: A work of art
      properties:
        name:
          type: string
          description: The work ID
        position:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
          required:
            - latitude
            - longitude
      required:
        - name
        - position

    WorkWithDistance:
      allOf:
        - $ref: "#/components/schemas/Work"
        - type: object
          properties:
            distance:
              type: number
              format: double
          required:
            - distance
