name: Continuous Deployment

on:
  push:
    branches:
      - main
      - 29-deploy-the-application
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build the docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to docker hub
        uses: docker/login-action@v1
        with:
          username: tomansion
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . -t museumgo_app

      - name: Tag the Docker image with latest and the tag name
        run: |
          docker tag museumgo_app tomansion/museumgo_app:latest
          # docker tag museumgo_app tomansion/museumgo_app:${{ github.sha }}

      - name: Upload Docker image to Docker Hub
        run: docker push tomansion/museumgo_app --all-tags

  deploy:
    needs: build
    name: Deploy to hosted server
    runs-on: ubuntu-latest
    steps:
      - name: Remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          password: ${{secrets.REMOTE_PASSWORD}}
          port: ${{secrets.REMOTE_PORT}}
          script: /usr/local/bin/update_museumgo_app/update_museumgo_app.sh
